name: Pre-release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '*.json'
      - '**/wcokey.txt'

concurrency:
  group: "pre-release"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Keystore
      run: |
        TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
        mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
        cp keystore.jks "${TMP_KEYSTORE_FILE_PATH}/prerelease_keystore.keystore"

    - name: Inject Google Services API Key
      run: sed -i 's/AIzaSyDUMMYKEYFORCIBUILDONLY000000000/${{ secrets.GOOGLE_SERVICES_API_KEY }}/g' app/google-services.json

    - name: Run Gradle
      run: ./gradlew assemblePrereleaseRelease androidSourcesJar makeJar > gradle.log 2>&1 || (cat gradle.log ; exit 1)
      env:
        SIGNING_KEY_ALIAS: "key0"
        SIGNING_KEY_PASSWORD: "cloudstream"
        SIGNING_STORE_PASSWORD: "cloudstream"
        MDBLIST_API_KEY: ${{ secrets.MDBLIST_API_KEY }}

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: prerelease-apks
        path: |
          app/build/outputs/apk/prerelease/release/*.apk
          app/build/libs/app-sources.jar
          app/build/classes.jar
