name: Test Run
on: [push, workflow_dispatch]

concurrency:
  group: "pre-release"
  cancel-in-progress: true

permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
